### ISSUE TITLE
Failed to load resource: the server responded with a status of 400 ().code: "auth/admin-restricted-operation"message: "This operation is restricted to administrators only."__proto__: Error

### ISSUE THREAD

**Issue by tuhinkole** [firebase/friendlyeats-web#101]
Failed to load resource: the server responded with a status of 400 ()

**Comment by samtstern** [comment]
@tuhinkole this is not enough information to help you.  Can you describe what you were trying to do and how you got to this error?  Code samples or links to the part of the codelab you were doing would be really helpful.

**Comment by mrmoses** [comment]
I got this on step "5 Run the local server"

After running `firebase serve --only hosting` there was a blank page at http://localhost:5000 with that error in the console.

I backtracked a little and found that Anonymous authentication was not enabled/saved (from step 2). Enabled and saved Anonymous sign-in, then refreshed http://localhost:5000 and had the correct page with no errors.

**Comment by jhuleatt** [comment]
Thanks for sharing, @mrmoses!
