### ISSUE TITLE
Error on page 4

### ISSUE THREAD

**Issue by lonerockz** [firebase/friendlyeats-web#103]
On page 4 it says you must do "firebase use --add" but I think you actually need to use firebase init.

**Comment by jhuleatt** [comment]
Hi @lonerockz, did you run into an error when running `firebase use --add`? `firebase init` has already been run (there is already a firebase.json in the git repo), so it shouldn't need to be run again.

`firebase use --add` is an important step for associating your code with the correct Firebase project.

**Comment by lonerockz** [comment]
I actually moved on to using Vue and Vuex with vuexfire so I can't remember if I got this working or not.
