### ISSUE TITLE
Remaining timer stops at step 6

### ISSUE THREAD

**Issue by Roolingen** [firebase/friendlyeats-web#104]
Device: PC
Operating system version: Win10/1909
Firebase SDK version: 7.8.1

What steps will reproduce the problem:
1. Start the lab
2. Go until step 6

What is the expected result? The estimated time should go until the end

What happens instead of that? The timer runs out on step 6

Please provide any other information below, and attach a screenshot if possible.

**Comment by samtstern** [comment]
@Roolingen thanks for noticing this!  Just fixed it.
