### ISSUE TITLE
FirestoreAdapter onDocumentModified doesn't update data on position change

### ISSUE THREAD

**Issue by s-hliao** [firebase/friendlyeats-web#125]
Steps to Reproduce:

- Set the FirestoreAdapter to a query capable of reaching two documents
- Attach adapter to a fully-implemented recyclerview capable of displaying data
- Update one document's data such that its position changes

Problem:
Though the document is moved to the correct position, the data that was changed will not be updated in the recyclerView.

Current Solution:
Added the line
`notifyItemChanged(change.getNewIndex());`
at the end of the case in onDocumentModified to update data on modified document.

**Comment by samtstern** [comment]
@s-hliao this seems to be mentioning Android concepts but you filed this on the repo for the web codelab.  Please re-file this on the correct repository.
