### ISSUE TITLE
help me if you can

### ISSUE THREAD

**Issue by ezequielmagi** [firebase/friendlyeats-web#147]
Please, i have the next issue:  
"Click Add Mock Data." it's never appears after editing "scripts/FriendlyEats.Data.js"

**Comment by AestheticArson** [comment]
The answer for this issue was listed in a closed case: [here](https://github.com/firebase/friendlyeats-web/issues/166#issuecomment-783650958)

**Comment by jhuleatt** [comment]
Thanks @AestheticArson!
