### ISSUE TITLE
codelab steps slightly out of order

### ISSUE THREAD

**Issue by rickshory** [firebase/friendlyeats-web#19]
In the codelab:
https://codelabs.developers.google.com/codelabs/firestore-web/#1
When you set up Firestore, if you choose the Databases option "locked", the codelab screen shown here:
https://codelabs.developers.google.com/codelabs/firestore-web/#3
Does not appear (and gives console errors), until changing the security rules in the following step:
https://codelabs.developers.google.com/codelabs/firestore-web/#4
Could be avoided either by advising to create the database not locked, or put the rule change step before the first serve.

**Comment by samtstern** [comment]
@rickshory thanks for this!  I'll update the first steo linked to advise on the selection.

**Comment by samtstern** [comment]
Changed!  You can see the new steps here:
https://codelabs.developers.google.com/codelabs/firestore-web/#1
