### ISSUE TITLE
Blank screen on step 4

### ISSUE THREAD

**Issue by vogelbeere** [firebase/friendlyeats-web#22]
I got to [step 4 of the Friendly Eats Codelab](https://codelabs.developers.google.com/codelabs/firestore-web/#3), and served my app on localhost, but just got a blank grey screen. 

I viewed the source and the code is there, but the "add mock data" button is not visible. It also has no event listeners other than `load` and `storage`.

When I ran the `firebase serve` command in the CLI, it seemed to hang partway through the process.

Also getting a "Failed to load resource" error on the Google auth API (I enabled Google Authentication in Step 3).

**Comment by vogelbeere** [comment]
Just deployed my app to the Firebase server and got the following error:

> Failed to load resource: the server responded with a status of 400 ()
> FriendlyEats.js:38 
> code: "auth/operation-not-allowed"
> message: "The given sign-in provider is disabled for this Firebase project. Enable it in the Firebase console, under the sign-in method tab of the Auth section."
> __proto__: Error

But I have enabled authentication in the Firebase console.

**Comment by samtstern** [comment]
Have you enabled all of the providers?  I think the important ones here are Google, Email, and Anonymous:

![image](https://user-images.githubusercontent.com/8466666/37534008-c3347c0a-2900-11e8-9318-7fb65445949a.png)

**Comment by vogelbeere** [comment]
I don't think the instructions mention that you should enable Anonymous. I will do that, thank you.

**Comment by vogelbeere** [comment]
I also missed out some crucial steps in the bit where it says "follow the instructions to set up your Firebase app" and takes you to a different screen (it would help if these were integrated into the Codelab).

**Comment by OboPT** [comment]
Hi @vogelbeere . Did you solve that issue? I have the same problem and i can´t understand what´s happening.

**Comment by vogelbeere** [comment]
> Hi @vogelbeere . Did you solve that issue? I have the same problem and i can´t understand what´s happening.

I cannot remember but I think I did by following what was suggested.

**Comment by mram45** [comment]
Seeing the same issue 

Followed all the instructions up to "Run Local Server".
on launching- http://localhost:5000

I see a screen with the following 
 You're seeing any restaurant located anywhere with any price sorted by rating

and not "add mock data" screen.

Am I missing something?

I have Anonymous  enabled. In the console for the index.html page I see  this error:

Uncaught Error in snapshot listener: FirebaseError: Missing or insufficient permissions

Should I be adding some other permissions?
