### ISSUE TITLE
Question about Page https://firebase.google.com/codelabs/firestore-web#5     Add Mock Data.

### ISSUE THREAD

**Issue by MarGer1962** [firebase/friendlyeats-web#221]
The text is in this chapter is as follows:
"The app will automatically generate a random set of restaurants objects, then call your addRestaurant function. However, you won't yet see the data in your actual web app because we still need to implement retrieving the data (the next section of the codelab)."

My question: where is the function "addRestaurant" situated?
I can't find it in the index.html file nor in the \scripts directory

Hoping for an answer

**Comment by jhuleatt** [comment]
Hi @MarGer1962, it's in `scripts/FriendlyEats.Data.js`: https://github.com/firebase/friendlyeats-web/blob/e87f6d2c98791e6855438639c3c283f5abd70c44/scripts/FriendlyEats.Data.js#L18-L22
