### ISSUE TITLE
on step 2 "the server responded with a status of 400"

### ISSUE THREAD

**Issue by Kamran21** [firebase/friendlyeats-web#23]
Its not clear for someone who is new to using firebase cli and the `firebase use --add`  if the project name created in the console should be specific or not. an example is needed! 

for example I gave my app the name friendlyEatsWeb and and run firebase use --add > picked "friendlyEatsWeb" >alias "defualt"> run "firebase serve"
And I all I get blank web page with console error "Failed to load resource: the server responded with a status of 400 ()".

Somehow I was right and I was able to proceed and I realized it after enabling anonymous login on step 4, So it is not a bug just a suggestion for a more detail's and examples for step 2

**Comment by michaelyfan** [comment]
Sorry to resurrect this thread, but I am just getting this error now, and it's unclear from the original post what the solution is. Can someone assist?

**Comment by onin91** [comment]
I'm having a problem in STEP 2 
---Error: HTTP Error: 404, The specified project was not found.

**Comment by nicolasgarnier** [comment]
The issue was that Anonymous Authentication was not enabled and you needed to enable it in the Firebase app console. I have re-worked the codelab instructions to make this more clear.
