### ISSUE TITLE
Error in Step 8, deploying indexes

### ISSUE THREAD

**Issue by vogelbeere** [firebase/friendlyeats-web#24]
In [Step 8, Deploying indexes](https://codelabs.developers.google.com/codelabs/firestore-web/#8), it gives the following JSON:

`{
 "indexes": [
   {
     "collectionId": "restaurants",
     "fields": [
       { "fieldPath": "city", "direction": "ASCENDING" },
       { "fieldPath": "avgRating", "direction": "DESCENDING" }
     ]
   },
   ...
 ]
}`

This gives an error and the app will not deploy.

> Error: All index fields must contain "mode": {"collectionId":"restaurants","fields":[{"fieldPath":"city","direction":"ASCENDING"},{"fieldPath":"avgRating","direction":"DESCENDING"}]}

Instead, the JSON should be: 

`{
 "indexes": [
   {
     "collectionId": "restaurants",
     "fields": [
       { "fieldPath": "city", "mode": "ASCENDING" },
       { "fieldPath": "avgRating", "mode": "DESCENDING" }
     ]
   }
 ]
}`

**Comment by samtstern** [comment]
@vogelbeere good catch, thank you!

**Comment by samtstern** [comment]
Fixed and published.
