### ISSUE TITLE
QuerySnapshot.docChanges has been changed from a property into a method

### ISSUE THREAD

**Issue by Vanluren** [firebase/friendlyeats-web#29]
This means that the `FriendlyEats.prototype.getDocumentsInQuery()` function is wrong. 

The function should be updated to reflect the change from a property to a method, like so:

```
FriendlyEats.prototype.getDocumentsInQuery = function(query, render) {
  query.onSnapshot(function(snapshot) {
    if (!snapshot.size){
      return render();
    }
    var changedDocs = snapshot.docChanges();
    changedDocs.forEach(function(change) {
      if (change.type === "added"){
        render(change.doc);
      }
    });
  });
};
```

I would love to take on a pull request, if that is okay?

**Comment by samtstern** [comment]
@Vanluren a pull request would be great!

**Comment by Vanluren** [comment]
Great, I'll take a look at it right away!

**Comment by samtstern** [comment]
Closed:
https://codelabs.developers.google.com/codelabs/firestore-web/#5
