### ISSUE TITLE
Show not working on dialogs

### ISSUE THREAD

**Issue by JoeLorenzoMontano** [firebase/friendlyeats-web#39]
I've been modifying the example and in the process of changing some of the dialogs I now get the following error. This was all working a couple days ago and I don't think any of my changes should have effected this.

Uncaught TypeError: that.dialogs.filter.show is not a function
    at HTMLDivElement.<anonymous> (FriendlyEats.View.js:53)
(anonymous) @ FriendlyEats.View.js:53

**Comment by phil-hz** [comment]
It's because the html pulls in the latest release of the MDC js, but that has breaking changes. Swapping out the css and JS to this should do it. Have submitted a PR  #40 
```
<link rel="stylesheet" href="https://unpkg.com/material-components-web@0.39.3/dist/material-components-web.min.css">
  <script src="https://unpkg.com/material-components-web@0.39.3/dist/material-components-web.js"></script>
```
Not going to look at any better of a fix than this as I'm only interested in studying the firebase aspects, not the MDC stuff.

**Comment by nicolasgarnier** [comment]
The fix has been merged. Thx!
