### ISSUE TITLE
More Codelab issues

### ISSUE THREAD

**Issue by danizord** [firebase/friendlyeats-web#5]
So, while doing the Codelab I've found some issues:

- [x] Naming: In CodeLab the project name is FireEats, while here it's FriendlyEats. Not a big issue, but some code snippets are failing due to wrong object prototype name.

- [x] Missing `getRestaurant()` implementation: the Codelab does not guide on how to implement `getRestaurant()`.

- [x] Missing full solution: the step 11 tells that we can find the full solution in `master` branch, but the master branch here has the initial app state.

- [x] Broken styles: the real app does not look like the pictures in the CodeLab. The "Guy Fireats" is not well sized, when `getAllRestaurants()` is not implemented it displays 2 useless stars at the bottom and when we implement it, it displays the restaurants but without their pictures.

![captura de tela 2017-10-03 as 17 07 02](https://user-images.githubusercontent.com/1850941/31146491-53cec07e-a85d-11e7-8d03-93ceec6ccfec.png)
![captura de tela 2017-10-03 as 17 04 46](https://user-images.githubusercontent.com/1850941/31146408-00979b4c-a85d-11e7-8ce5-50d0e288376f.png)
![captura de tela 2017-10-03 as 17 04 20](https://user-images.githubusercontent.com/1850941/31146407-0073bbe6-a85d-11e7-80d4-c3af83cb3bae.png)

**Comment by abehaskins** [comment]
On it.

**Comment by abehaskins** [comment]
Alright, sorry about all this. Seems like an older version got merged with a newer version during pre-launch migration. Please [take another look](https://codelabs.developers.google.com/codelabs/firestore-web/).

**Comment by abehaskins** [comment]
(also please pull the latest `styles/` from my commit to get it to look right)

**Comment by danizord** [comment]
Looks great! Thanks @abehaskins! Just one more thing (the last I promise 😛 ): the `addReview()` method of step 10 should be renamed to `addRating()` to match the code :)
