### ISSUE TITLE
Error FriendlyEats.Data.js:40 Uncaught TypeError: renderer.display is not a function

### ISSUE THREAD

**Issue by jatu-studiobox** [firebase/friendlyeats-web#51]
Hi,

I follow CodeLab - Firestore Web. I found an error below

**Uncaught TypeError: renderer.display is not a function
    at FriendlyEats.Data.js:40
    at Array.forEach (<anonymous>)
    at Object.next (FriendlyEats.Data.js:36)
    at next (index.esm.js:20461)
    at index.esm.js:18425**

As a result friendlyeats-web cannot display all item in Firestore.

I'm not sure, Firestore has any update so friendlyeats-web is not compatible.

Regards,

**Comment by lagmanzaza** [comment]
#49 
My friend found a solution which fixes it.

**Comment by nicolasgarnier** [comment]
Sorry about that guys, it looks like we updated the instructions document too soon. I just pushed the new code that goes with the new instructions.

Now `renderer.display` and `renderer.remove` should work.
