### ISSUE TITLE
⚠  Setup required, please run: firebase setup:emulators:firestore

### ISSUE THREAD

**Issue by Yatima-Kagurazaka** [firebase/friendlyeats-web#57]
After `firebase serve` at https://codelabs.developers.google.com/codelabs/firestore-web/#4 ,

```
$ firebase serve

=== Serving from '/foobar'...

⚠  Setup required, please run: firebase setup:emulators:firestore

Error: An unexpected error has occurred.
```

We should change the command into `firebase serve --only hosting` to avoid confusion.

**Comment by morganchen12** [comment]
Fixed and published; the new version should be available soon.

Thanks!
