### ISSUE TITLE
says addReview instead of addRating

### ISSUE THREAD

**Issue by mechanical-turk** [firebase/friendlyeats-web#6]
There's a part in the codelab that reads: 

```
Add the following code in the FriendlyEats.prototype.addReview() method.
```

There is no method named `addReview`. However, there is one, named `addRating`, at line 23 of FriendlyEats.Data.js. At that point of the codelab, that is the only function that is left to be filled, and the variables used in the codelab matches the signature of the function.

**Comment by abehaskins** [comment]
Great catch and [it's done](https://codelabs.developers.google.com/codelabs/firestore-web/#9). Thanks so much for the bug.
