### ISSUE TITLE
Error posting mock ratings

### ISSUE THREAD

**Issue by manucho007** [firebase/friendlyeats-web#7]
There seems to be some kind of problem with the version of Firestore used in the codelab, whenever I post the mock data i get this errors. 
![image](https://user-images.githubusercontent.com/17936451/31469773-1a3e8ace-aeb1-11e7-8f4f-d87a52f0c151.png)

**Comment by abehaskins** [comment]
This is actually expected due to how we write the data, does the data fail to write?

**Comment by manucho007** [comment]
No, it prints the data fine, thank you!
