### ISSUE TITLE
Could not reach Cloud Firestore backend (section 6)

### ISSUE THREAD

**Issue by abelpronet** [firebase/friendlyeats-web#73]
Hello,

I have an issue in the section 6 (write data to cloud Firestore.

When I click Add Mock Data and I navigate to the Cloud Firebase tab, there are no collection available.

I have checked the console on Google Chrome bowser and send me the following error:

[2019-06-18T09:05:07.698Z]  @firebase/firestore: Firestore (5.10.0): Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: FirebaseError: [code=failed-precondition]: The Cloud Firestore API is not available for Cloud Datastore projects.
This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.

I don't know if Im doing something wrong or if you need more information about mi code or what Im doing

**Comment by jhuleatt** [comment]
At the moment you can't have Datastore and Firestore enabled in the same project. Please try creating a new Firebase project to get rid of the error. If that doesn't work, [file a support ticket](https://firebase.google.com/support).
