### ISSUE TITLE
Problem getting the filtered data

### ISSUE THREAD

**Issue by manucho007** [firebase/friendlyeats-web#8]
There seems to be a problem getting the filtered data.
![image](https://user-images.githubusercontent.com/17936451/31469938-c3a17540-aeb1-11e7-8699-bb61fb2705f8.png)
As you can see I have the data in my firestore project, and I created the indexes.
![image](https://user-images.githubusercontent.com/17936451/31469983-f45ae9a0-aeb1-11e7-8c2b-d12ff3159293.png)
but I still don't get any response, even if I I'm clearly calling the first item from the list
![image](https://user-images.githubusercontent.com/17936451/31470021-22f6f984-aeb2-11e7-8bd9-c6af230b263d.png)

**Comment by nicolasgarnier** [comment]
Thanks @manucho007, there was indeed an error in the filtering code. Just fixed it :)

**Comment by nicolasgarnier** [comment]
Basically when we were not filtering by price we were adding a `price=0` filter anyways which never returns any results (all entries have a 1-4 price).

**Comment by davie-robertson** [comment]
I had fixed it downstream, but the code from here in codelabs has overwritten my fix
https://github.com/firebase/quickstart-js/pull/171

**Comment by samtstern** [comment]
cc @abehaskins
