### ISSUE TITLE
Wrong usage document in firestore section

### ISSUE THREAD

**Issue by isamu** [firebase/friendlyeats-web#81]
In https://codelabs.developers.google.com/codelabs/firestore-web/index.html#1
You wrote
> The app uses Cloud Firestore to save the chat messages and receive new chat messages.

But this sample app is not chat app. 
For example,

 The app uses Cloud Firestore to save restaurant info and receive updated restaurant's rating.

**Comment by jhuleatt** [comment]
Thanks @isamu! I've updated the codelab to say this:

> The app uses Cloud Firestore to save and receive restaurant information and ratings.
