### ISSUE TITLE
ratingCount has to changed to numRatings

### ISSUE THREAD

**Issue by olegkvyatkovskiy** [firebase/friendlyeats-web#91]
https://codelabs.developers.google.com/codelabs/firestore-web/#10
ratingCount has to changed to numRatings

**Comment by mrmoses** [comment]
and `averageRating` is now `avgRating`

Step 11 mentions:

> values of `averageRating` and `ratingCount`

But the variables in the code are `avgRating` and `numRatings`

**Comment by samtstern** [comment]
@jhuleatt can you take a look at this when you get back?

**Comment by jhuleatt** [comment]
Thank you @olegkvyatkovskiy and @mrmoses! I've republished the codelab with the corrected variable names.
